### ISSUE TITLE
What type of encryption use?

### ISSUE THREAD

**Issue by racmanuel** [RIIDEAC/NOM-035-STPS-2018-51#2]
I try build a user generator to insert into database but i don't know what type of encryption use! :(
I try with this:
password_hash("demoprueba", PASSWORD_DEFAULT)."\n";
but the result is not the same as the one inserted in the file demoNom035.sql

¡Intento construir un generador de usuarios para insertar en la base de datos pero no sé qué tipo de cifrado utilizo! :(
Intento con esto:
password_hash("demoprueba", PASSWORD_DEFAULT)."\n";
pero el resultado no es el mismo que el insertado en el archivo demoNom035.sql

**Comment by OsvaldoGDelRio** [comment]
El generador es password_hash ( string $password , integer $algo [, array $options ] ) : string
https://www.php.net/manual/es/function.password-hash.php

Para verificar:
password_verify ( string $password , string $hash ) : bool
https://www.php.net/manual/es/function.password-verify.php

El resultado nunca es el mismo, es la belleza de password_hash
